### ISSUE TITLE
Relay > Purchase > Premium Relay flow

### ISSUE THREAD

**Issue by groovecoder** [mozilla/fx-private-relay#838]
## Tasks
* [x] Mock-ups
   * [Pre-purchase dashboard with new upgrade/purchase call-outs](https://www.figma.com/file/jp318GsWGaR3RALWNqv7cp/Prospector-MVP-Workflows?node-id=520%3A2390)
   * [New "no aliases" onboarding UI in dashboard](https://www.figma.com/file/jp318GsWGaR3RALWNqv7cp/Prospector-MVP-Workflows?node-id=520%3A6859)
   * [Payment flow with new icon & description](https://www.figma.com/file/jp318GsWGaR3RALWNqv7cp/Prospector-MVP-Workflows?node-id=520%3A5901)
   * [New Post-purchase dashboard with new aggregate stats banner and "get domain" call-out](https://www.figma.com/file/jp318GsWGaR3RALWNqv7cp/Prospector-MVP-Workflows?node-id=520%3A2987)
* [ ] Implementation done
   * [x] Update top promo for purchasing Pack (#844)
   * [ ] Update "onboarding" UI when dashboard is empty 
   * [x] Update bottom promo for purchasing Pack (#844)
   * [x] Update Privacy Pack product in SubPlat
   * [x] Enable Relay premium on stage server
   * [x] Update premium dashboard "get your email domain" call-out
   * [ ] Add top banner of aggregated email stats
* [ ] QA first-pass
* [ ] l10n done
* [ ] Support team trained

### Server environments ready:
* [ ] [Dev server](https://dev.fxprivaterelay.nonprod.cloudops.mozgcp.net/)
* [ ] [Stage server](https://stage.firefoxmonitor.nonprod.cloudops.mozgcp.net/)
###
* [ ] As a user, I want to sign up for Relay with an existing Firefox Account.
* [ ] As a user, I want to sign up for Relay with a new Firefox Account.
* [ ] As a user, I want to sign into Relay.
* [ ] As a signed-in user, I want to create up to 5 email aliases.
* [ ] As a signed-in user, I cannot create more than 5 email aliases.
* [ ] As a signed-in user, I want to see a banner at the top of Relay to upgrade to the Mozilla Privacy Pack.
* [ ] As a signed-in user, I want to see a banner at the bottom of Relay to upgrade to the Mozilla Privacy Pack.
* [ ] As a signed-in user, I want to use the top upgrade banner to buy Mozilla Privacy Pack
   * Note: can use test stripe card on the `payments-stage` server: any name, 4242-4242-4242-4242, any future expiration, any cvc
   * After purchase, click "Continue to download" should take the user back to Relay
   * The user is now a "subscriber"
* [ ] As a signed-in subscriber, I want to create 6 or more email aliases.
* [ ] As a signed-in subscriber, I want to register ("get" in the UI) my own email domain.

**Comment by maxxcrawford** [comment]
@groovecoder Timing wise, I think we need to push this line item: 

> Update "onboarding" UI when dashboard is empty

**Comment by EMMLynch** [comment]
Completed / Closing
